// SQL autocomplete schema for Monaco Editor
export const SQL_KEYWORDS = [
  "SELECT",
  "FROM",
  "WHERE",
  "INSERT",
  "UPDATE",
  "DELETE",
  "CREATE",
  "DROP",
  "ALTER",
  "TABLE",
  "INDEX",
  "VIEW",
  "JOIN",
  "INNER",
  "LEFT",
  "RIGHT",
  "OUTER",
  "ON",
  "AS",
  "AND",
  "OR",
  "NOT",
  "IN",
  "LIKE",
  "BETWEEN",
  "IS",
  "NULL",
  "ORDER",
  "BY",
  "GROUP",
  "HAVING",
  "OFFSET",
  "DISTINCT",
  "COUNT",
  "SUM",
  "AVG",
  "MIN",
  "MAX",
]

export const SQL_FUNCTIONS = [
  "COUNT",
  "SUM",
  "AVG",
  "MIN",
  "MAX",
  "CONCAT",
  "SUBSTRING",
  "UPPER",
  "LOWER",
  "TRIM",
  "LENGTH",
  "ROUND",
  "FLOOR",
  "CEIL",
  "NOW",
  "DATE",
  "YEAR",
  "MONTH",
  "DAY",
]

// Sample table schemas for autocomplete
export const SQL_TABLES = {
  users: {
    columns: ["id", "name", "email", "created_at", "updated_at"],
    description: "User accounts table",
  },
  posts: {
    columns: ["id", "user_id", "title", "content", "published_at", "created_at"],
    description: "Blog posts table",
  },
  comments: {
    columns: ["id", "post_id", "user_id", "content", "created_at"],
    description: "Post comments table",
  },
  categories: {
    columns: ["id", "name", "slug", "description"],
    description: "Content categories table",
  },
  tags: {
    columns: ["id", "name", "slug"],
    description: "Content tags table",
  },
}
